#! /bin/bash

BAT_NO=0
# BAT_NO=1

acpiOutput=`acpi -V | grep "Battery $BAT_NO"`
status=`echo $acpiOutput | head -n 1 | sed "s/Battery $BAT_NO\: //" | cut -d"," -f1`
[[ $status == "Discharging" ]] && ss=↓ || ss=↑
perc=`echo $acpiOutput | head -n 1 | sed "s/Battery $BAT_NO\: //" | cut -d"," -f2 | sed "s/ //" | sed "s/%//"`
remaining=`echo $acpiOutput | grep -Eo "[0-9]+:[0-9]+"`
# Treshold varia a seconda della capacità massima di carica della batteria, per tenere conto del suo invecchiamento
treshold=`bc <<< "105 - $(acpi -V | grep "last full capacity" | grep -o ".[0-9]*%" | sed "s/%//")"`

echo "$perc% $ss, $remaining"
echo "$perc"

case ${BLOCK_BUTTON} in
    3) urxvt -e bash -c "i3 floating toggle >/dev/null; acpi -V; sleep 30";;
    *)
esac

if [ $status == "Discharging" ] && [ $perc -le $treshold ]; then
    exit 33
fi
