#! /bin/bash

# . ${HOME}/.cache/wal/colors.sh # colorscheme from wal
tdf="/home/vic/ownCloud/Dropbox/todo.txt"

tdn=$(cat "$tdf" | grep -v "^x" | grep "due:`date +%F`" | wc -l)
tdun=$(cat "$tdf" | grep -v "^x" | grep "due:`date +%F`" | grep "^(" | wc -l)
echo $tdn, $tdun! # Real text
echo # Short text

# Color
if [[ $tdun -gt 0 ]]; then
    exit 33
elif [[ $tdn -gt 0 ]]; then
    echo "#d68787"
else
    echo "$green"
fi
