#! /bin/bash

. ${HOME}/.cache/wal/colors.sh # colorscheme from wal
tdf="/home/vic/ownCloud/Dropbox/todo.txt"

case ${BLOCK_BUTTON} in
    3) urxvt -e bash -c "i3 floating toggle && view $tdf";;
    *) ;;
esac

tdn=$(cat "$tdf" | grep -v "^x" | grep "due:`date +%F`" | wc -l)
tdun=$(cat "$tdf" | grep -v "^x" | grep "due:`date +%F`" | grep "^(" | wc -l)
echo $tdn, $tdun! # Real text
echo # Short text

# Color
if [[ $tdun -gt 0 ]]; then
    exit 33
elif [[ $tdn -gt 0 ]]; then
    echo $color1
else
    echo "$green"
fi
