# MPV config file
# vim:fdm=marker

# Codec {{{
# af=lavfi=[loudnorm=I=-22:LRA=2:TP=-1.5]
# af=lavfi=[dynaudnorm=f=75:g=25:p=0.55]
# }}}

# General {{{
cache-unlink-files=whendone
volume-max=300
gpu-context=x11egl
embeddedfonts=no
sub-font=sans-serif
osd-font=sans-serif
# }}}

# Input {{{
input-ipc-server=/tmp/mpvsocket
input-media-keys=yes
# }}}

# Appearance {{{
border=yes
osc=yes
osd-bar=yes
# }}}

# Subtitle {{{
ytdl-raw-options=sub-format=en,write-sub=
sub-auto=fuzzy
slang=en
# }}}

# Performance {{{
video-sync=display-resample
correct-downscaling=no
cscale-antiring=0
cscale=bilinear
deband=no
dither-depth=no
dscale=bilinear
hwdec-codecs=all
hwdec=auto-safe
interpolation=no
scale-antiring=0
scale=bilinear
sigmoid-upscaling=no
vd-lavc-dr=yes
vo=gpu
# }}}
