filetype plugin indent on                " Specific indentation rules depending on file type
filetype plugin on                       " Filetype plugin
syntax enable                            " Enable syntax Highlighting


source <sfile>:h/init/plugin.vim
source <sfile>:h/init/mappings.vim
source <sfile>:h/init/options.vim
source <sfile>:h/init/abbrev.vim
source <sfile>:h/init/appearance.vim
source <sfile>:h/init/auto.vim
source <sfile>:h/init/functions.vim
source <sfile>:h/init/uni.vim

if has ("nvim")
	source <sfile>:h/init/nvim-only.vim
endif
