#! /usr/bin/env bash

IFS=$'\n'
FILE=$P/Notes/spese-2020.txt


getTags(){
    grep -o "@.[[:alnum:]]*" $FILE | sort | uniq
}

# Shamefully inefficient

real_total=0
for tag in $(getTags); do
    total=$(awk -F' ' -- "/$tag/{s+=\$2}END{print s}" $FILE)
    real_total=$(bc <<< "$real_total + $total")
    # printf "%-20s %.1f€\n" "$tag" "$total"
    printf "%.1f€\t\t%s\n" "$total" "$tag"
done
printf "%s\t\t%s\n" "----" "====================" 
printf "%.1f€\t\t%s\n" "$(grep -v '@.[[:alnum:]]*' $FILE | grep -v "^#" | awk -F' ' -- '{s+=$2}END{print s}')" "Uncategorized"
printf "%.1f€\t\t%s\n\n" $real_total "TOTAL"

echo -e "Ultimo aggiornamento: $(ls -al $FILE | cut -d" " -f6-8)\n"
