#! /bin/bash

# Based on doi2bib script
## Original author: Conner McDaniel
## https://github.com/connermcd/bin
## MIT license

DEFAULT_BIB_FILE=/home/vic/pCloudDrive/Libreria/default.bib
DEFAULT_LIBRARY_LOCATION=$P/Libreria

doi2bib() {
    wget -qO- "http://api.crossref.org/works/$1/transform/application/x-bibtex"
}

isbn2bib(){
    # Get the entire html code of the page
    htmlBlob=$(wget -qO- "https://www.ottobib.com/isbn/$1/bibtex")
    # The actual bibtex entry is stored inside a textarea, so we grep from the @ of the bibtex entry until the end of the textarea
    echo $htmlBlob | grep -o "@.*</textarea" | sed "s,</textarea,," | sed "s/}, /},\n/g" | sed "s/, author/,\nauthor/g" | sed "s,} },}\n},"
}

pubmed2bib(){
    echo "Not implemented yet"
}

usage(){
cat<<HEREDOC
$(basename $0) - get Bibtex information
USAGE
    $(basename $0) [options] [-d DOI] [-i ISBN]
OPTION
    -A  Append bibtex entry to a bib file stored in the default library. See CONFIGURATION
    -d  Get bibtex entry from doi number
    -i  Get bibtex entry from ISBN
    -p  Get bibtex entry from PMid

CURRENT CONFIGURATION
    Library location: $DEFAULT_LIBRARY_LOCATION
    Default bibtex file: $DEFAULT_BIB_FILE
    Accepted bibtex files: $(find $DEFAULT_LIBRARY_LOCATION  -maxdepth 1 -type f | grep bib | sed "s,$DEFAULT_LIBRARY_LOCATION/,,g" | tr '\n' ' ')

HEREDOC
}


while [[ $# -gt 0 ]]; do
    case $1 in
        "-A") APPEND_ENTRY=true; APPEND_TO=$2 shift;;
        "-d") doi2bib $2 ;;
        "-i") isbn2bib $2;;
        "-p") pubmed2bib $2;;
        "-h") usage;;
        *) usage;;
    esac
    shift; shift;
done

if [[ $APPEND_ENTRY == "true" ]]; then
    echo "Not implemented yet"
    # Scegliere il file corretto al quale appendere
    # Controllare che la chiave non ci sia già
        # Chiave non c'è => appendo
        # Chiave c'è => errore + stampo chiave
fi
