#! /usr/bin/env bash
# Define a word using treccani vocabulary

set -e

VOCAB_PROVIDER_URL="https://www.treccani.it/vocabolario" 	# Vocab provider
PANDOC_CUSTOM_WRITER="$HOME/.pandoc/terminal.lua"			# Pandoc custom writer to format output text
PANDOC_WRITER=plain											# Pandoc fallback writer
GREP_RULE="tc-title.*DEBUG"									# Rule for scraping definition from webpage

$(tty -s) && [[ -f $PANDOC_CUSTOM_WRITER ]] && PANDOC_WRITER="$PANDOC_CUSTOM_WRITER"

if [[ $# -gt 0 ]]; then

	(curl -s "$VOCAB_PROVIDER_URL/$1" | tr -d "\n" | grep -o "$GREP_RULE" | pandoc -f html -t $PANDOC_WRITER --wrap=preserve | grep -v "tc-title\">") 2>/dev/null

	[[ $1 == "-e" ]] && (shift; curl https://www.treccani.it/enciclopedia/$1 | tr -d '\n' | grep -o "text spiega.*class=\"sinottico" | pandoc -f html -t $PANDOC_WRITER --wrap=preserve | grep -v "text spiega" ) 2>/dev/null && exit 0

else
	echo <<-EOH
	Usage:
		$(basename $0) <word>
		$(basename $0) -e <word>
	EOH

fi
