#!/usr/bin/env bash

GONG="/home/vic/pCloudDrive/Res/ping.opus"

notify() {
	# [[ $(uname) == "Darwin" ]] && echo "osascript -e 'display alert \"GONG! 🚨\" message \"$@\"'" ||

	echo "notify-send --urgency=critical \"PING!\" \"$mess\" && play -nq -t alsa synth 0.07 sine 2000"

}

function gong () {
    case $1 in
        # "-g")
        #     shift
        #     time=$1
        #     shift
        #     mess=$*
        #     echo at $time <<<"notify-send --urgency=critical \"GONG!\" \"$mess\"";;
        *)
            time=$1
            shift
            mess=$*
			at $time <<< $(notify $mess);;
    esac
}

usage() {
	cat <<-EOH
	receive reminder at specified time

	USAGE
		$(basename $0) <time> <message>
	EOH
}

[[ $# -gt 0 ]] && gong $* || usage
