#! /usr/bin/env bash

(
ext="txt"
base_dir="$1"
shift
cd $base_dir # Useful if you want to run `make` directly inside vim
note=`find -type f -regex ".*\.\(txt\|md\)" -not -wholename "*Archivio*" | fzf --exact --height=100% -1 --header="$base_dir" --preview='head -$LINES {}' --print-query --query="$*"`
if [[ $? -eq 0 ]]; then
    # edit note
    $EDITOR "`tail -n1 <<< "$note"`"
elif [[ $? -eq 1 ]]; then
    if [[ $note != "" ]]; then
        # add new note
        touch "$note.$ext"
        $EDITOR "$note.$ext"
    else
        exit 1
    fi
fi
)
