#! /usr/bin/env bash
# Notational velocity clone (www.notational.net) using bash, fzf and vim

(
ext="md"
base_dir="${1:-.}"

shift
cd $base_dir
note=$(find -type f -regex ".*\.\(txt\|md\)" -not -wholename "*Archivio*" -not -wholename "*/_/*" | sort | fzf -1 --height=100% --header="$base_dir" --preview='head -$LINES {}' --print-query --query="$*")

if [[ $? -eq 0 ]]; then         # If the note exists
    # edit note
    ${EDITOR:-vim} "`tail -n1 <<< "$note"`"
    # ${EDITOR:-vim} "$note"
elif [[ $? -eq 1 ]]; then       # If the note doesn't exist
    if [[ $note != "" ]]; then
        folder=$(dirname "$note")
        file=$(basename "$note")
        [[ ! $folder == "." ]] && mkdir "$folder" # If $note contains a directory which is not the pwd, then create it

        echo "<!-- $(date) -->"  >> "$note.$ext" # Create note and write date
        ${EDITOR:-vim} "$note.$ext"
    else
        exit 1
    fi
fi
)
