#! /bin/bash 
# vim: fdm=marker

# Api --  https://source.unsplash.com  {{{
# https://source.unsplash.com/random/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/likes/{SIZE}
# https://source.unsplash.com/collection/{COLLECTION ID}/{SIZE}
# https://source.unsplash.com/category/{CATEGORY}/?{SEARCH,TERM}
# https://source.unsplash.com/?{KEYWORD}
# https://source.unsplash.com/{daily|weekly}
# https://source.unsplash.com/featured/?{KEYWORD[,KEYWORD]}
# https://source.unsplash.com/1600x900/{?SEARCH,TERM}
# https://source.unsplash.com/{PHOTO ID}/1600x900
# }}}

# Collezioni {{{
COLLECTION_NUMBER="1778533" # Collezione mia
# COLLECTION_NUMBER="1007074"
# COLLECTION_NUMBER="1186428"
# COLLECTION_NUMBER="142376"
# COLLECTION_NUMBER="142563"  # stelline
# COLLECTION_NUMBER="1657511"
# COLLECTION_NUMBER="1816977"
# COLLECTION_NUMBER="1912959"
# COLLECTION_NUMBER="1922729" # Beautiful shots from above
# COLLECTION_NUMBER="198884"
# COLLECTION_NUMBER="201"
# COLLECTION_NUMBER="217569"
# COLLECTION_NUMBER="220388"
# COLLECTION_NUMBER="235"     # Best NASA
# COLLECTION_NUMBER="266986"
# COLLECTION_NUMBER="289662"
# COLLECTION_NUMBER="311432"
# COLLECTION_NUMBER="311766"  # Autumn
# COLLECTION_NUMBER="326594"
# COLLECTION_NUMBER="3403104" # Autumn is here
# COLLECTION_NUMBER="353649"
# COLLECTION_NUMBER="357786"
# COLLECTION_NUMBER="429524"
# COLLECTION_NUMBER="452289"
# COLLECTION_NUMBER="573009"
# COLLECTION_NUMBER="629911"
# COLLECTION_NUMBER="827743"
# COLLECTION_NUMBER="862387"
# COLLECTION_NUMBER="921374"  # Pattern
# COLLECTION_NUMBER="4994801"
# COLLECTION_NUMBER="452289"
# COLLECTION_NUMBER="1971015"
# COLLECTION_NUMBER="215418"
# COLLECTION_NUMBER="162468"
# COLLECTION_NUMBER="1520527"
# COLLECTION_NUMBER="909298"
# COLLECTION_NUMBER="438041"  # Christmas
# COLLECTION_NUMBER="9737757" # Lo-fi inspo
# COLLECTION_NUMBER="1957016"
# COLLECTION_NUMBER="483251"
# COLLECTION_NUMBER="1245"
COLLECTION_NUMBER="994"
# user=stbuccia
# }}}

# Settings

post-process () {
    # convert $1 -type grayscale $1
    echo
}


# wget -O $HOME/img "https://source.unsplash.com/user/$user/"
# wget -O $HOME/img "https://source.unsplash.com/collection/$COLLECTION_NUMBER/1600x900"
# wget -O $HOME/img "https://source.unsplash.com/featured/"

wget --no-check-certificate -O $HOME/img "https://source.unsplash.com/collection/$COLLECTION_NUMBER/"
post-process img.png
