#! /bin/bash 
# vim: fdm=marker

# Api Reference {{{
# https://source.unsplash.com
# https://source.unsplash.com/random/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/likes/{SIZE}
# https://source.unsplash.com/collection/{COLLECTION ID}/{SIZE}
# https://source.unsplash.com/category/{CATEGORY}/?{SEARCH,TERM}
# https://source.unsplash.com/?{KEYWORD}
# https://source.unsplash.com/{daily|weekly}
# https://source.unsplash.com/featured/?{KEYWORD[,KEYWORD]}
# https://source.unsplash.com/1600x900/{?SEARCH,TERM}
# https://source.unsplash.com/{PHOTO ID}/1600x900
# }}}

# Collezioni {{{
# COLLECTION_NUMBER="1778533" # Collezione mia
# COLLECTION_NUMBER="1007074"
# COLLECTION_NUMBER="1186428"
# COLLECTION_NUMBER="142376"
# COLLECTION_NUMBER="142563"  # stelline
# COLLECTION_NUMBER="1657511"
# COLLECTION_NUMBER="1816977"
# COLLECTION_NUMBER="1912959"
# COLLECTION_NUMBER="1922729" # Beautiful shots from above
# COLLECTION_NUMBER="198884"
# COLLECTION_NUMBER="201"
# COLLECTION_NUMBER="217569"
# COLLECTION_NUMBER="220388"
# COLLECTION_NUMBER="235"     # Best NASA
# COLLECTION_NUMBER="266986"
# COLLECTION_NUMBER="289662"
# COLLECTION_NUMBER="311432"
# COLLECTION_NUMBER="311766"  # Autumn
# COLLECTION_NUMBER="326594"
# COLLECTION_NUMBER="3403104" # Autumn is here
# COLLECTION_NUMBER="353649"
# COLLECTION_NUMBER="357786"
# COLLECTION_NUMBER="429524"
# COLLECTION_NUMBER="452289"
# COLLECTION_NUMBER="573009"
# COLLECTION_NUMBER="629911"
# COLLECTION_NUMBER="827743"
# COLLECTION_NUMBER="862387"
# COLLECTION_NUMBER="921374"  # Pattern
# COLLECTION_NUMBER="4994801"
# COLLECTION_NUMBER="452289"
# COLLECTION_NUMBER="1971015"
# COLLECTION_NUMBER="215418"
COLLECTION_NUMBER="162468" # Earth from above
# COLLECTION_NUMBER="1520527"
# COLLECTION_NUMBER="909298"
# COLLECTION_NUMBER="438041"  # Christmas
# COLLECTION_NUMBER="9737757" # Lo-fi inspo
# COLLECTION_NUMBER="1957016"
# COLLECTION_NUMBER="483251"
# COLLECTION_NUMBER="1245"
# COLLECTION_NUMBER="994" # Sea
# COLLECTION_NUMBER="1930316" # Hipster
# COLLECTION_NUMBER=1118894 # Superior interior
# COLLECTION_NUMBER=1028668 # Outdoor
# COLLECTION_NUMBER="397770"
# COLLECTION_NUMBER="21106240" # Lofi
# COLLECTION_NUMBER="3805071" #Northern Lights

user=evicinelli
user=stbuccia
# }}}

# Settings
# RES="1920x1080"
RES="1440x900"

UNSPLASH_URL="https://source.unsplash.com/user/evicinelli/likes/$RES"
# UNSPLASH_URL="https://source.unsplash.com/user/$user/$RES"
# UNSPLASH_URL="https://source.unsplash.com/collection/$COLLECTION_NUMBER/$RES"

# Post process img?
post-process () {
	echo
    # convert $1 -type grayscale $1
	# feh --bg-scale ~/img
	# wal -c
	# wal -i ~/img

	[[ $(uname) == "Darwin" ]] && killall Dock
}

curl -k -L $UNSPLASH_URL -o $HOME/.img.jpeg
post-process img.png
