#!/bin/sh
xmodmap "/home/vic/.Xmodmap"

dropbox start &
nm-applet &
compton -b &
xfce4-power-manager &
# feh --bg-fill ~/img.png


which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
exec fluxbox

fbsetbg -b -solid dark "#582c83" &
