#!/bin/sh
xmodmap "/home/vic/.Xmodmap"

dropbox start &
nm-applet &
compton -b &
xfce4-power-manager &
# feh --bg-fill ~/img.png
fbsetroot -solid dark "#cc0000"


which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi
exec fluxbox
