#!/bin/bash

# Time in minutes to fall asleep; the mean is 15 minutes
falling_asleep=20

# The length of a cycle **in minutes**, standard value is 90
length=90

mLength=`bc<<<"$length*60"`
mAdded=`bc<<<"$falling_asleep*60"`
now=`date +%s`
alarmTime=${1:-"8:30"}
wakeup=`date +%s -d "tomorrow $alarmTime"`

# Calcoliamo gli scaglioni
for i in {1..10}; do
    wakeup=`bc <<< "$wakeup - $mLength"`
    # Togliere il 3600 toglie l'ora dovuta al diverso fuso
    echo "vai a letto alle $(date +%H:%M -d "@`bc <<< "$wakeup-$mAdded"`") per dormire `date +%H\ \o\r\e\ \e\ %M\ \m\i\n -d "@$(bc <<< "$i*$mLength - 3600")"` ($i cicli)"
    [[ `bc <<< "$wakeup - $mLength"` -lt $now ]] && exit
done
