#! /bin/bash

(
#cd $NOTES
ext="md"
base_dir="$1"
# new_key="ctrl-n"
cd $base_dir
shift
note=`fzf -1 --header="$base_dir" --preview='head -$LINES {}' --print-query --query="$*"`
if [[ $? -eq 0 ]]; then
    # edit note
    $EDITOR "`tail -n1 <<< "$note"`"
elif [[ $? -eq 1 ]]; then
    if [[ $note != "" ]]; then
        # add new note
        touch "$note.txt"
        $EDITOR "$note.$ext"
    else
        exit 0
    fi
fi
)
