#! /bin/bash
export DISPLAY=:0
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/vic/.fzf/bin

acpiOutput=`acpi -V | grep "Battery 0"`
status=`echo $acpiOutput | grep "Battery 0" | head -n 1 | sed "s/Battery 0\: //" | cut -d"," -f1`
perc=`echo $acpiOutput | grep "Battery 0" | head -n 1 | sed "s/Battery 0\: //" | cut -d"," -f2 | sed "s/ //" | sed "s/%//"`
remaining=`echo $acpiOutput | grep "Battery 0" | head -n 1 | sed "s/Battery 0\: //" | cut -d"," -f3 | sed "s/ remaining.*//"`
# Treshold varia a seconda della capacità massima di carica della batteria, per tenere conto dell'invecchiamento della stessa
treshold=`bc <<< "95 - $(acpi -V | grep "last full capacity" | grep -o ".[0-9]*%" | sed "s/%//")"` 

# echo $treshold

if [ $status == "Discharging" ] && [ $perc -le $treshold ] ; then
    notify-send DUNST_COMMAND_RESUME
    notify-send --urgency=critical "BATTERIA SCARICAAAAAA ($perc%) " "Mettila in carica, muvèt!!"
fi

