#! /bin/bash

push="{
  \"push\": {
    \"conversation_iden\": \"+1 303 555 1212\",
    \"message\": \"Hello!\",
    \"package_name\": \"com.pushbullet.android\",
    \"source_user_iden\": \"ujpah72o0\",
    \"target_device_iden\": \"ujpah72o0sjAoRtnM0jc\",
    \"type\": \"messaging_extension_reply\"
  },
}"

curl --header "Access-Token: $PB_TOKEN" \
         --header "Content-Type: application/json" \
         --data-binary "{"push":$push,"type":"push"}" \
         --request POST https://api.pushbullet.com/v2/ephemerals

