#! /bin/bash 

FONT="Inconsolata 12"

# Kill dunst
killall dunst

# Do we have wal?
if [[ -e $HOME/.cache/wal/colors.sh ]]; then
    source "${HOME}/.cache/wal/colors.sh"

    # Start dunst with color sourced
    /usr/bin/dunst \
        -lb "${color0:=#444444}" \
        -nb "$color3" \
        -cb "$color2" \
        -lf "${color15:=#CCCCCC}" \
        -bf "$color0" \
        -cf "$color0" \
        -nf "$color0" \
        -fn $FONT \
        -key "mod4+x" \
        -all_key "mod4+shift+x" \
        -history_key "mod4+n" \
        -geometry "300x5-30+30" >/dev/null &
else
    /usr/bin/dunst >/dev/null &
fi

# vim: fdm=marker
