#! /bin/bash 
#	get wallpaper randomly from unsplash, apply it, and using pywal build a matching colorscheme

# API DOC --  https://source.unsplash.com  {{{
# https://source.unsplash.com/random/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/{SIZE}
# https://source.unsplash.com/user/{USERNAME}/likes/{SIZE}
# https://source.unsplash.com/collection/{COLLECTION ID}/{SIZE}
# https://source.unsplash.com/category/{CATEGORY}/?{SEARCH,TERM}
# https://source.unsplash.com/?{KEYWORD}
# https://source.unsplash.com/{daily|weekly}
# https://source.unsplash.com/featured/?{KEYWORD[,KEYWORD]}
# https://source.unsplash.com/1600x900/{?SEARCH,TERM}
# https://source.unsplash.com/{PHOTO ID}/1600x900
# }}}

# Collezion[e/i] {{{

# COLLECTION_NUMBER="1912959"
# COLLECTION_NUMBER="629911"
# COLLECTION_NUMBER="198884"
# COLLECTION_NUMBER="1778533" # Collezione mia
# COLLECTION_NUMBER="289662"
# COLLECTION_NUMBER="217569"
# COLLECTION_NUMBER="201"
# COLLECTION_NUMBER="266986"
#  COLLECTION_NUMBER="142563" # stelline
# COLLECTION_NUMBER="452289"
# COLLECTION_NUMBER="862387"
# COLLECTION_NUMBER="1007074"
# COLLECTION_NUMBER="921374"
# COLLECTION_NUMBER="142376"
# COLLECTION_NUMBER="326594"
# COLLECTION_NUMBER="1657511"
# COLLECTION_NUMBER="353649"
# }}}

COLLECTION_NUMBER="1922729" # Beautiful shots from above

# Settings
PARAMS=$*

# Grabbing wallpaper from unsplash
rm $HOME/.img
wget -O $HOME/.img "https://source.unsplash.com/collection/$COLLECTION_NUMBER/1600x900"


# Do we have pywal installed?
if [[ -x $HOME/.local/bin/wal ]]; then
    # I3 and terminal theming
    /home/vic/.local/bin/wal $PARAMS -c -i $HOME/.img
else
    # We don't :(
    feh --bg-scale $HOME/.img
fi

# Theme notification
bash $HOME/Dotfiles/script/start-dunst

# vim: fdm=marker
