[colors.primary]
background = '#181211'
foreground = '#ede0dd'
 
[colors.cursor]
text = '#ede0dd'
cursor = '#d8c2bd' 
 
[colors.vi_mode_cursor]
text = '#181211'
cursor = '#ffb4a4' 
 
[colors.search.matches]
foreground = '#534340' 
background = '#dbc48c' 
 
[colors.search.focused_match]
foreground = '#534340' 
background = '#ffb4a4' 
 
[colors.footer_bar]
foreground = '#534340' 
background = '#ede0dd' 
 
[colors.hints.start]
foreground = '#534340' 
background = '#e7bdb4' 
 
[colors.hints.end]
foreground = '#534340' 
background = '#e7bdb4' 
 
[colors.selection]
text = '#181211'
background = '#ffb4a4'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb4a4' 
yellow = '#9c4330' 
blue = '#ffb4a4' 
magenta = '#dbc48c' 
cyan = '#e7bdb4' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 