[colors.primary]
background = '#f6fbf3'
foreground = '#181d18'

[colors.cursor]
text = '#f6fbf3'
cursor = '#181d18'

[colors.vi_mode_cursor]
text = '#f6fbf3'
cursor = '#005529'

[colors.search.matches]
foreground = '#dae6d9'
background = '#264491'

[colors.search.focused_match]
foreground = '#dae6d9'
background = '#005529'

[colors.footer_bar]
foreground = '#dae6d9'
background = '#2d322d'

[colors.hints.start]
foreground = '#dae6d9'
background = '#46664c'

[colors.hints.end]
foreground = '#dae6d9'
background = '#46664c'

[colors.selection]
text = '#3f4940'
background = '#dae6d9'


[colors.normal]
black   = '#dae6d9'
red     = '#ba1a1a'
green   = '#005529'
yellow  = '#46664c'
blue    = '#264491'
magenta = '#288348'
cyan    = '#5b7b5f'
white   = '#181d18'


[colors.bright]
black   = '#6f7a6f'
red     = '#ba1a1a'
green   = '#005529'
yellow  = '#46664c'
blue    = '#264491'
magenta = '#288348'
cyan    = '#5b7b5f'
white   = '#181d18'


[colors.dim]
black   = '#dae6d9'
red     = '#ba1a1a'
green   = '#005529'
yellow  = '#46664c'
blue    = '#264491'
magenta = '#288348'
cyan    = '#5b7b5f'
white   = '#181d18'
