[colors.primary]
background = '#f9faf4'
foreground = '#191c19'
 
[colors.cursor]
text = '#191c19'
cursor = '#414941' 
 
[colors.vi_mode_cursor]
text = '#f9faf4'
cursor = '#066d37' 
 
[colors.search.matches]
foreground = '#dde5da' 
background = '#3a656e' 
 
[colors.search.focused_match]
foreground = '#dde5da' 
background = '#066d37' 
 
[colors.footer_bar]
foreground = '#dde5da' 
background = '#2e312e' 
 
[colors.hints.start]
foreground = '#dde5da' 
background = '#506352' 
 
[colors.hints.end]
foreground = '#dde5da' 
background = '#506352' 
 
[colors.selection]
text = '#f9faf4'
background = '#066d37'
 
 
[colors.normal]
black = '#181818' 
red = '#ba1a1a' 
green = '#066d37' 
yellow = '#81d997' 
blue = '#066d37' 
magenta = '#3a656e' 
cyan = '#506352' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 