[general]
import = [ "~/.config/alacritty/themes/noctalia.toml", ]

[window]
decorations = "None"
padding = { x = 12, y = 12 }
opacity = 1.0

[scrolling]
history = 3023

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false

[bell]
duration = 0

[font]
size=12
offset={x = 0, y = 2}
